# SAMPLES=$1
# SIZE=$2
# INTER_ARRIVAL=$3
# READ_RATIO=$4
# SAS=$5
# DISTRIBUTION=$6
# MEAN=$7
# STDEV=$8
# CONCURRENCY=$9

# ./generator ${SAMPLES} ${SIZE} ${INTER_ARRIVAL} ${READ_RATIO} ${SAS} ${DISTRIBUTION} ${MEAN} ${STDEV} ${CONCURRENCY} > output/trace.csv

./generator $SAMPLES $SIZE $INTER_ARRIVAL $READ_RATIO $SAS $DISTRIBUTION $MEAN $STDEV $CONCURRENCY > output/trace.csv

